; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = task2_1A

; 全課題で共通のボード設定
[env]
platform = atmelavr
board = uno
framework = arduino

; --- 各課題の設定 ---
[env:task2_1A]
build_src_filter = +<task2_1A.cpp>

[env:task2_2A]
build_src_filter = +<task2_2A.cpp>

[env:task2_3A]
build_src_filter = +<task2_3A.cpp>

[env:task2_4A]
build_src_filter = +<task2_4A.cpp>

[env:task2_5A]
build_src_filter = +<task2_5A.cpp>

[env:task2_5B]
build_src_filter = +<task2_5B.cpp>

[env:task3_1A]
build_src_filter = +<task3_1A.cpp>

[env:task3_2A]
build_src_filter = +<task3_2A.cpp>

[env:task3_2B]
build_src_filter = +<task3_2B.cpp>

[env:task4_1A]
build_src_filter = +<task4_1A.cpp>

; 第4章（Servoライブラリが必要な課題）
[env:task4_2A]
build_src_filter = +<task4_2A.cpp>
lib_deps = 
    arduino-libraries/Servo@^1.2.2

[env:task4_2B]
build_src_filter = +<task4_2B.cpp>
lib_deps = 
    arduino-libraries/Servo@^1.2.2
